services:
  - type: pserv
    name: db
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: db/Dockerfile
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: secret
      - key: POSTGRES_DB
        value: webshop
      - key: DB_PORT
        value: "5432"
    plan: free

  - type: web
    name: backend
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_USER
        value: admin
      - key: DB_PASS
        value: secret
      - key: DB_NAME
        value: webshop
      - key: DB_PORT
        value: "5432"
      - key: BACKEND_PORT
        value: "5000"
      - key: JWT_SECRET
        value: mysecretkey
    plan: free
    healthCheckPath: /

  - type: web
    name: frontend-responsive
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: frontend-responsive/Dockerfile
    envVars:
      - key: FRONTEND_PORT
        value: "80"
    plan: free

  - type: web
    name: frontend-adaptive
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: frontend-adaptive/Dockerfile
    envVars:
      - key: FRONTEND_PORT
        value: "80"
      - key: DB_HOST
        value: db
      - key: DB_USER
        value: admin
      - key: DB_PASS
        value: secret
      - key: DB_NAME
        value: webshop
    plan: free
