services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-cvitdebipnbc73etc6h0-a
      - key: DB_USER
        value: admin
      - key: DB_PASS
        value: QkGmujNaqft9H03XNVkRPhzna8OyjIjY
      - key: DB_NAME
        value: dbwebshop
      - key: DB_PORT
        value: "5432"
      - key: JWT_SECRET
        value: mysecretkey
    plan: free

  - type: web
    name: frontend-responsive
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: frontend-responsive/Dockerfile
    envVars:
      - key: FRONTEND_PORT
        value: "80"
    plan: free

  - type: web
    name: frontend-adaptive
    env: docker
    repo: https://github.com/helhar1234/my-webshop
    dockerfilePath: frontend-adaptive/Dockerfile
    envVars:
      - key: FRONTEND_PORT
        value: "80"
      - key: DB_HOST
        value: dpg-cvitdebipnbc73etc6h0-a
      - key: DB_USER
        value: admin
      - key: DB_PASS
        value: QkGmujNaqft9H03XNVkRPhzna8OyjIjY
      - key: DB_NAME
        value: dbwebshop
      - key: VITE_API_URL
        value: https://my-webshop-6ek5.onrender.com/api

    plan: free
